services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:letmein@db:5432/postgres?schema=public
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - fs_data:/var/lib/postgresql/data

volumes:
  fs_data: