import type { MetaFunction } from "react-router";

// This file is generated by react-router
export interface RouteArgs {}

export interface LoaderArgs extends RouteArgs {
  request: Request;
}

export interface ActionArgs extends RouteArgs {
  request: Request;
}

export interface MetaArgs extends RouteArgs {}

export type Meta = MetaFunction<typeof loader>;

// Loader function (placeholder for now)
async function loader(_args: LoaderArgs) {
  return null;
}

export { loader };
