import { Product } from "./product.types";

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "Polo React",
    imgSrc: "/images/polos/polo-react.png",
    price: 20,
    description:
      "Viste tu pasión por React con estilo y comodidad en cada línea de código.",
    category: "polos",
    isOnSale: false,
  },
  {
    id: "2",
    title: "Polo JavaScript",
    imgSrc: "/images/polos/polo-js.png",
    price: 20,
    description:
      "Deja que tu amor por JavaScript hable a través de cada hilo de este polo.",
    category: "polos",
    isOnSale: false,
  },
  {
    id: "3",
    title: "Polo Node.js",
    imgSrc: "/images/polos/polo-node.png",
    price: 20,
    description:
      "Conéctate al estilo con este polo de Node.js, tan robusto como tu código.",
    category: "polos",
    isOnSale: false,
  },
  {
    id: "4",
    title: "Polo TypeScript",
    imgSrc: "/images/polos/polo-ts.png",
    price: 20,
    description:
      "Tipa tu estilo con precisión: lleva tu pasión por TypeScript en cada hilo.",
    category: "polos",
    isOnSale: false,
  },
  {
    id: "5",
    title: "Polo Backend Developer",
    imgSrc: "/images/polos/polo-backend.png",
    price: 25,
    description:
      "Domina el servidor con estilo: viste con orgullo tu título de Backend Developer.",
    category: "polos",
    isOnSale: false,
  },
  {
    id: "6",
    title: "Polo Frontend Developer",
    imgSrc: "/images/polos/polo-frontend.png",
    price: 25,
    description:
      "Construye experiencias con estilo: luce con orgullo tu polo de Frontend Developer.",
    category: "polos",
    isOnSale: false,
  },
  {
    id: "7",
    title: "Polo Full-Stack Developer",
    imgSrc: "/images/polos/polo-fullstack.png",
    price: 25,
    description:
      "Domina ambos mundos con estilo: lleva tu título de FullStack Developer en cada línea de tu look.",
    category: "polos",
    isOnSale: false,
  },
  {
    id: "8",
    title: "Polo It's A Feature",
    imgSrc: "/images/polos/polo-feature.png",
    price: 15,
    description:
      "Cuando el bug se convierte en arte: lleva con orgullo tu polo 'It's a feature'.",
    category: "polos",
    isOnSale: true,
  },
  {
    id: "9",
    title: "Polo It Works On My Machine",
    imgSrc: "/images/polos/polo-works.png",
    price: 15,
    description:
      "El clásico del desarrollador: presume tu confianza con 'It works on my machine'.",
    category: "polos",
    isOnSale: true,
  },
  {
    id: "s1",
    category: "stickers",
    title: "JavaScript Logo Sticker",
    imgSrc: "/images/polos/polo-react.png",
    price: 2.99,
    description: "Classic JavaScript hexagon logo sticker",
    isOnSale: false,
  },
  {
    id: "s2",
    category: "stickers",
    title: "React Native Sticker",
    imgSrc: "/images/polos/polo-react.png",
    price: 2.49,
    description: "React Native logo with mobile devices",
    isOnSale: false,
  },
  {
    id: "s3",
    category: "stickers",
    title: "Git Branch Master",
    imgSrc: "/images/polos/polo-react.png",
    price: 3.99,
    description: "Large Git branching visualization",
    isOnSale: false,
  },
  {
    id: "s4",
    category: "stickers",
    title: "Python Powered",
    imgSrc: "/images/polos/polo-react.png",
    price: 2.99,
    description: "Official Python programming language logo",
    isOnSale: false,
  },
  {
    id: "s5",
    category: "stickers",
    title: "Docker Whale",
    imgSrc: "/images/polos/polo-react.png",
    price: 2.99,
    description: "Cute Docker whale carrying containers",
    isOnSale: false,
  },
  {
    id: "s6",
    category: "stickers",
    title: "Linux Penguin",
    imgSrc: "/images/polos/polo-react.png",
    price: 2.49,
    description: "Tux the Linux penguin",
    isOnSale: false,
  },
  {
    id: "s7",
    category: "stickers",
    title: "Full Stack Developer Pack",
    imgSrc: "/images/polos/polo-react.png",
    price: 4.99,
    description: "Collection of popular web development logos",
    isOnSale: false,
  },
  {
    id: "s8",
    category: "stickers",
    title: "VS Code Logo",
    imgSrc: "/images/polos/polo-react.png",
    price: 2.49,
    description: "Visual Studio Code editor logo",
    isOnSale: false,
  },
  {
    id: "s9",
    category: "stickers",
    title: "GitHub Octocat",
    imgSrc: "/images/polos/polo-react.png",
    price: 2.99,
    description: "GitHub's famous Octocat mascot",
    isOnSale: false,
  },
  {
    id: "s10",
    category: "stickers",
    title: "Stack Overflow",
    imgSrc: "/images/polos/polo-react.png",
    price: 2.99,
    description: "Developer's best friend logo",
    isOnSale: false,
  },
  {
    id: "m1",
    category: "tazas",
    title: "Git Command Mug",
    imgSrc: "/images/polos/polo-react.png",
    price: 14.99,
    description: "Start your day with essential Git commands",
    isOnSale: false,
  },
  {
    id: "m2",
    category: "tazas",
    title: "Coffee.js Mug",
    imgSrc: "/images/polos/polo-react.png",
    price: 13.99,
    description: "JavaScript code that prints coffee",
    isOnSale: false,
  },
  {
    id: "m3",
    category: "tazas",
    title: "Python Loop Mug",
    imgSrc: "/images/polos/polo-react.png",
    price: 12.99,
    description: "While not coffee: drink()",
    isOnSale: false,
  },
  {
    id: "m4",
    category: "tazas",
    title: "React State Mug",
    imgSrc: "/images/polos/polo-react.png",
    price: 15.99,
    description: "useState(coffee)",
    isOnSale: false,
  },
  {
    id: "m5",
    category: "tazas",
    title: "Code Bug Mug",
    imgSrc: "/images/polos/polo-react.png",
    price: 13.99,
    description: "No bugs, just features",
    isOnSale: false,
  },
  {
    id: "m6",
    category: "tazas",
    title: "SQL Query Mug",
    imgSrc: "/images/polos/polo-react.png",
    price: 14.99,
    description: "SELECT * FROM coffee WHERE energy = LOW",
    isOnSale: false,
  },
  {
    id: "m7",
    category: "tazas",
    title: "Docker Container Mug",
    imgSrc: "/images/polos/polo-react.png",
    price: 15.99,
    description: "Containerize your coffee",
    isOnSale: false,
  },
  {
    id: "m8",
    category: "tazas",
    title: "Terminal Command Mug",
    imgSrc: "/images/polos/polo-react.png",
    price: 13.99,
    description: "sudo make coffee",
    isOnSale: false,
  },
  {
    id: "m9",
    category: "tazas",
    title: "Stack Overflow Mug",
    imgSrc: "/images/polos/polo-react.png",
    price: 14.99,
    description: "Copy Paste Expert",
    isOnSale: false,
  },
  {
    id: "m10",
    category: "tazas",
    title: "CSS Mug",
    imgSrc: "/images/polos/polo-react.png",
    price: 13.99,
    description: "This mug is #000000",
    isOnSale: false,
  },
];
